/**
 * The committed dashboards and alert rules must describe metrics that REALLY
 * EXIST (#460).
 *
 * This is the regression guard for the exact defect the maintainer rejected:
 * "ships Grafana dashboards and an Alertmanager rule, but ... the metrics never
 * exist, so the probe-down alert can never fire."
 *
 * So this test does not read the ops files in isolation. It first drives the
 * real anchor pipeline and the real sentinel probe to produce every series they
 * are capable of producing, scrapes the shared Prometheus registry, and only
 * then checks that every `scada_*` metric named in ops/alertmanager/
 * control-loop-rules.yml and ops/grafana/control-loop-latency.json is present
 * in that scrape. A rule referring to a metric nobody emits fails here.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import yaml from 'js-yaml';
import type { JsonRpcProvider } from 'ethers';

import { AnchorPipeline, type AnchorLatencyEvent } from '../anchor-pipeline';
import type { AnchorContractLike } from '../relayer';
import { ControlLoopLatencyProbe } from '../latency-probe.js';
import { publishControlLoopProbeStatus, probeUpGauge } from '../latency-probe.js';
import { registry } from '../../metrics/prometheus.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../../..');
const RULES_PATH = path.join(repoRoot, 'ops/alertmanager/control-loop-rules.yml');
const DASHBOARD_PATH = path.join(repoRoot, 'ops/grafana/control-loop-latency.json');

const rulesText = readFileSync(RULES_PATH, 'utf8');
const dashboardText = readFileSync(DASHBOARD_PATH, 'utf8');

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

/** Metric names referenced in a file, with _bucket/_sum/_count normalised away. */
function referencedMetrics(text: string): Set<string> {
  const names = new Set<string>();
  for (const raw of text.match(/scada_[a-z0-9_]+/g) ?? []) {
    names.add(raw.replace(/_(bucket|sum|count)$/, ''));
  }
  return names;
}

/**
 * Whether a scrape carries at least one SAMPLE for a metric — not merely its
 * HELP/TYPE header. Prometheus alerts evaluate samples, so a header-only metric
 * is exactly the "series that never exists" this test exists to catch.
 */
function hasSample(text: string, metric: string): boolean {
  const escaped = metric.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`^${escaped}(_bucket|_sum|_count)?[{ ]`, 'm').test(text);
}

interface PromRule {
  alert?: string;
  expr?: string;
  for?: string;
}
interface PromRuleFile {
  groups: Array<{ name: string; rules: PromRule[] }>;
}

/** Every series the instrument can produce, generated by running it for real. */
let scrape = '';

describe('control-loop observability config matches what is produced (#460)', () => {
  const pipelines: AnchorPipeline[] = [];

  beforeAll(async () => {
    registry.reset();

    const contract: AnchorContractLike = {
      anchor: Object.assign(
        async () => {
          await sleep(20);
          return { wait: async () => ({ hash: '0xabc', blockNumber: 10, gasUsed: 21000n }) };
        },
        { estimateGas: async () => 100000n },
      ),
    };
    const provider = {
      getFeeData: async () => ({ gasPrice: 1_000_000_000n }),
      getBlockNumber: async () => 12,
    } as unknown as JsonRpcProvider;

    // 1. A real pipeline anchoring a real (sentinel-driven) batch: produces the
    //    stage histograms, the round-trip histogram, the SLO gauge, and the
    //    confirmed cycle counter.
    const ok = new AnchorPipeline({
      pipeline: { maxBatchSize: 1 },
      relayerDeps: { contract, provider },
      latencySource: 'ops-check',
    });
    pipelines.push(ok);
    await ok.start();

    const probe = new ControlLoopLatencyProbe(ok, { siteId: 'ops-check' });
    probe.start();
    const confirmed = new Promise<AnchorLatencyEvent>((resolve) =>
      ok.once('anchor-latency', resolve),
    );
    await probe.flipOnce();
    await confirmed;
    // probe_up must read 1 while the probe runs.
    expect(probeUpGauge.get()).toBe(1);
    probe.stop();

    // 2. A pipeline whose anchor fails: produces the non-confirmed cycle
    //    outcome the "not confirming" rule is written against.
    const bad = new AnchorPipeline({
      pipeline: { maxBatchSize: 1 },
      relayer: { maxRetries: 1 },
      relayerDeps: { contract, provider },
      latencySource: 'ops-check-failed',
    });
    pipelines.push(bad);
    await bad.start();
    const originalSign = bad.signer.signMerkleRoot.bind(bad.signer);
    bad.signer.signMerkleRoot = async (root: string) => {
      const sig = await originalSign(root);
      return { ...sig, signature: sig.signature.replace(/^../, 'ff') };
    };
    const failed = new Promise<AnchorLatencyEvent>((resolve) => bad.once('anchor-latency', resolve));
    await bad.ingestEvent({
      id: 'plant-evt-1',
      timestamp: 1_700_000_000_000,
      type: 'reading',
      source: 'sensor-1',
      data: { value: 1 },
    });
    await failed;

    // 3. The probe is stopped again, so probe_up is published as 0 — the state
    //    the ControlLoopProbeDown alert must be able to see.
    publishControlLoopProbeStatus();
    scrape = registry.metrics();
  }, 30_000);

  afterAll(async () => {
    while (pipelines.length) await pipelines.pop()!.stop();
  });

  it('produced every control-loop series the instrument defines', () => {
    for (const metric of [
      'scada_control_loop_stage_latency_seconds',
      'scada_control_loop_roundtrip_latency_seconds',
      'scada_control_loop_stage_slo_ok',
      'scada_control_loop_cycles_total',
      'scada_control_loop_probe_up',
      'scada_control_loop_probe_flips_total',
      'scada_control_loop_sentinel_roundtrip_seconds',
    ]) {
      expect(scrape).toContain(`# HELP ${metric} `);
      expect(hasSample(scrape, metric), `${metric} has no samples`).toBe(true);
    }
    // Non-empty: each of these has at least one sample line, not just a header.
    expect(scrape).toMatch(/scada_control_loop_stage_latency_seconds_count\{stage="confirm"/);
    expect(scrape).toMatch(/scada_control_loop_cycles_total\{source="ops-check-failed",outcome="failed"\} 1/);
    expect(scrape).toMatch(/scada_control_loop_sentinel_roundtrip_seconds_count 1/);
  });

  it('the alert rules parse and every metric they name is produced', () => {
    const parsed = yaml.load(rulesText) as PromRuleFile;
    expect(parsed.groups).toHaveLength(1);
    const rules = parsed.groups[0].rules;
    expect(rules.length).toBeGreaterThan(0);
    for (const rule of rules) {
      expect(rule.alert).toBeTruthy();
      expect(rule.expr).toBeTruthy();
    }

    for (const metric of referencedMetrics(rulesText)) {
      expect(
        hasSample(scrape, metric),
        `alert rules reference ${metric}, which produced no samples`,
      ).toBe(true);
    }
  });

  it('the dashboard parses and every metric it names is produced', () => {
    const dashboard = JSON.parse(dashboardText) as { dashboard: { panels: unknown[] } };
    expect(dashboard.dashboard.panels.length).toBeGreaterThan(0);

    for (const metric of referencedMetrics(dashboardText)) {
      expect(
        hasSample(scrape, metric),
        `dashboard references ${metric}, which produced no samples`,
      ).toBe(true);
    }
  });

  it('neither the rules nor the dashboard reference the unmeasurable tick stage', () => {
    expect(rulesText).not.toContain('stage="tick"');
    expect(dashboardText).not.toContain('stage=\\"tick\\"');
    expect(scrape).not.toContain('stage="tick"');
  });

  it('the probe-down alert is written against a series that actually exists', () => {
    const parsed = yaml.load(rulesText) as PromRuleFile;
    const probeDown = parsed.groups[0].rules.find((r) => r.alert === 'ControlLoopProbeDown');
    expect(probeDown).toBeDefined();
    expect(probeDown!.expr!.trim()).toBe('scada_control_loop_probe_up == 0');

    // The condition the alert tests for is representable: with the probe not
    // running, the scrape carries the gauge with the value 0, so `== 0` selects
    // a real sample. (Contrast with a rate() over a histogram that was never
    // created, which returns an empty vector and can never fire.)
    expect(scrape).toContain('scada_control_loop_probe_up 0');
    expect(probeUpGauge.get()).toBe(0);
  });

  it('the stage-budget alert is written against the SLO gauge with a 5m window', () => {
    const parsed = yaml.load(rulesText) as PromRuleFile;
    const breach = parsed.groups[0].rules.find((r) => r.alert === 'ControlLoopStageBudgetBreached');
    expect(breach).toBeDefined();
    expect(breach!.expr!.trim()).toBe('scada_control_loop_stage_slo_ok == 0');
    expect(breach!.for).toBe('5m');
  });
});
