# OxSCADA GitHub Labels Configuration
# Use with: gh label import labels.yml

# Learning Track Labels
- name: "track:frontend"
  color: "7057ff"
  description: "Track A: Frontend Engineering"
- name: "track:backend"
  color: "0e8a16"
  description: "Track B: Backend Engineering"
- name: "track:blockchain"
  color: "fbca04"
  description: "Track C: Blockchain Engineering"
- name: "track:systems"
  color: "d93f0b"
  description: "Track D: Systems Engineering"
- name: "track:automation"
  color: "006b75"
  description: "Track E: Industrial Automation"
- name: "track:quality"
  color: "1d76db"
  description: "Track Q: Quality Engineering"

# Difficulty Labels
- name: "difficulty:beginner"
  color: "c5def5"
  description: "Level 1 - Foundation"
- name: "difficulty:intermediate"
  color: "bfd4f2"
  description: "Level 2 - Core Competency"
- name: "difficulty:advanced"
  color: "d4c5f9"
  description: "Level 3 - Advanced"
- name: "difficulty:expert"
  color: "e99695"
  description: "Level 4 - Expert"

# Phase Labels
- name: "phase:6-realtime"
  color: "0052cc"
  description: "Phase 6: Real-Time Industrial Communication"
- name: "phase:7-batch"
  color: "5319e7"
  description: "Phase 7: ISA-88 Batch Runtime"
- name: "phase:8-hmi"
  color: "b60205"
  description: "Phase 8: HMI/SCADA Visualization"
- name: "phase:9-os"
  color: "d93f0b"
  description: "Phase 9: OxSCADA Operating System"
- name: "phase:10-decentralized"
  color: "0e8a16"
  description: "Phase 10: Decentralized Network"
- name: "phase:11-ai"
  color: "006b75"
  description: "Phase 11: AI & Digital Twins"

# Type Labels
- name: "type:feature"
  color: "a2eeef"
  description: "New feature or enhancement"
- name: "type:bugfix"
  color: "d73a4a"
  description: "Bug fix"
- name: "type:docs"
  color: "0075ca"
  description: "Documentation"
- name: "type:test"
  color: "e4e669"
  description: "Test coverage"
- name: "type:refactor"
  color: "fef2c0"
  description: "Code refactoring"
- name: "type:security"
  color: "b60205"
  description: "Security related"

# Status Labels
- name: "status:ready"
  color: "0e8a16"
  description: "Ready to start"
- name: "status:blocked"
  color: "d93f0b"
  description: "Blocked by dependency"
- name: "status:needs-review"
  color: "fbca04"
  description: "Needs review"
- name: "good-first-issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help-wanted"
  color: "008672"
  description: "Extra attention needed"

# Component Labels
- name: "component:server"
  color: "c2e0c6"
  description: "Server/backend"
- name: "component:client"
  color: "c5def5"
  description: "Client/frontend"
- name: "component:blockchain"
  color: "fef2c0"
  description: "Blockchain/contracts"
- name: "component:kernel"
  color: "f9d0c4"
  description: "Linux kernel"
- name: "component:gateway"
  color: "d4c5f9"
  description: "Protocol gateway"
- name: "component:agents"
  color: "bfdadc"
  description: "Autonomous agents"

# Epic Label
- name: "epic"
  color: "3e4b9e"
  description: "Large initiative with sub-issues"
