apiVersion: v1
kind: ConfigMap
metadata:
  name: oxscada-config
  labels:
    app.kubernetes.io/part-of: oxscada
data:
  NODE_ENV: production
  SERVER_PORT: "{{ .Values.server.port }}"
  GATEWAY_PORT: "{{ .Values.gateway.port }}"
  CLIENT_PORT: "{{ .Values.client.port }}"
  RATE_LIMITER_BACKEND: "{{ .Values.rateLimiter.backend }}"
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
