name: Feature Request
description: Propose a new feature for OxSCADA
title: "[Feature] "
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for contributing to OxSCADA! Please describe the feature you'd like to see.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of OxSCADA does this affect?
      options:
        - "Server (Backend API)"
        - "Client (Frontend UI)"
        - "Blockchain (Smart Contracts)"
        - "Gateway (Protocol Drivers)"
        - "Kernel (OxSCADA OS)"
        - "Agents (Autonomous Agents)"
        - "Blueprints (Code Generation)"
        - "Documentation"
        - "Multiple / Cross-cutting"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a [user type], I want to [action] so that [benefit]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the solution you'd like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: Alternative approaches and why they weren't chosen...
    validations:
      required: false

  - type: dropdown
    id: industrial-relevance
    attributes:
      label: Industrial Relevance
      description: How does this relate to industrial control systems?
      options:
        - "Direct - Core SCADA/HMI/PLC functionality"
        - "Indirect - Supports industrial workflows"
        - "Infrastructure - General platform improvement"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing issues/PRs
          required: true
        - label: This aligns with the OxSCADA roadmap
          required: true
