/**
 * Batch Anchoring Service Test Suite
 * 
 * Generated by Agentic-QE Worker (Phase 3)
 * 
 * Coverage targets:
 * - MerkleTree: Construction, proof generation, verification
 * - BatchAnchoringService: Queue management, batching, stats
 * - Edge cases: Empty batches, timer triggers, config updates
 * - Integration scenarios: Full event → batch → anchor flow
 */

import { describe, it, expect, beforeEach, afterEach, vi, type Mock } from 'vitest';
import { sha256 } from '../crypto/index';

// ============================================================================
// MOCK BLOCKCHAIN SERVICE
// ============================================================================

const mockBlockchainService = {
  isEnabled: vi.fn().mockReturnValue(true),
  anchorBatchRoot: vi.fn().mockResolvedValue('0xmocktxhash123'),
};

vi.mock('../blockchain', () => ({
  blockchainService: mockBlockchainService,
}));

// Import after mocks are set up
import {
  MerkleTree,
  BatchAnchoringService,
  type BatchableEvent,
  type BatchConfig,
  type BatchResult,
  type BatchStats,
} from '../batch-anchoring';

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function createTestEvent(id: string, overrides: Partial<BatchableEvent> = {}): BatchableEvent {
  return {
    id,
    assetId: `asset-${id}`,
    eventType: 'ALARM',
    payload: { value: Math.random() * 100, unit: 'celsius' },
    timestamp: new Date(),
    ...overrides,
  };
}

function generateEvents(count: number): BatchableEvent[] {
  return Array.from({ length: count }, (_, i) => createTestEvent(`event-${i + 1}`));
}

// ============================================================================
// MERKLE TREE TESTS
// ============================================================================

describe('MerkleTree', () => {
  describe('Construction', () => {
    it('should construct tree from single leaf', () => {
      const data = ['hello'];
      const tree = new MerkleTree(data);
      
      expect(tree.getRoot()).toBeDefined();
      expect(tree.getRoot()).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should construct tree from multiple leaves', () => {
      const data = ['leaf1', 'leaf2', 'leaf3', 'leaf4'];
      const tree = new MerkleTree(data);
      
      expect(tree.getRoot()).toBeDefined();
      expect(tree.getRoot()).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should handle empty data array', () => {
      const tree = new MerkleTree([]);
      
      // Empty tree should return a valid hash
      expect(tree.getRoot()).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should handle odd number of leaves', () => {
      const data = ['leaf1', 'leaf2', 'leaf3'];
      const tree = new MerkleTree(data);
      
      expect(tree.getRoot()).toBeDefined();
      expect(tree.getRoot()).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should produce consistent root for same data', () => {
      const data = ['a', 'b', 'c'];
      const tree1 = new MerkleTree(data);
      const tree2 = new MerkleTree(data);
      
      expect(tree1.getRoot()).toBe(tree2.getRoot());
    });

    it('should produce different root for different data', () => {
      const tree1 = new MerkleTree(['a', 'b']);
      const tree2 = new MerkleTree(['a', 'c']);
      
      expect(tree1.getRoot()).not.toBe(tree2.getRoot());
    });

    it('should produce different root for different order', () => {
      const tree1 = new MerkleTree(['a', 'b']);
      const tree2 = new MerkleTree(['b', 'a']);
      
      expect(tree1.getRoot()).not.toBe(tree2.getRoot());
    });
  });

  describe('Proof Generation', () => {
    it('should generate valid proof for first leaf', () => {
      const data = ['leaf1', 'leaf2', 'leaf3', 'leaf4'];
      const tree = new MerkleTree(data);
      
      const proof = tree.getProof(0);
      
      expect(proof).toBeInstanceOf(Array);
      expect(proof.length).toBeGreaterThan(0);
      proof.forEach(hash => {
        expect(hash).toMatch(/^0x[a-f0-9]{64}$/);
      });
    });

    it('should generate valid proof for last leaf', () => {
      const data = ['leaf1', 'leaf2', 'leaf3', 'leaf4'];
      const tree = new MerkleTree(data);
      
      const proof = tree.getProof(3);
      
      expect(proof).toBeInstanceOf(Array);
      expect(proof.length).toBeGreaterThan(0);
    });

    it('should generate valid proof for middle leaf', () => {
      const data = ['a', 'b', 'c', 'd'];
      const tree = new MerkleTree(data);
      
      const proof = tree.getProof(2);
      
      expect(proof.length).toBeGreaterThan(0);
    });

    it('should generate single-element proof for two leaves', () => {
      const data = ['left', 'right'];
      const tree = new MerkleTree(data);
      
      const proofLeft = tree.getProof(0);
      const proofRight = tree.getProof(1);
      
      expect(proofLeft.length).toBe(1);
      expect(proofRight.length).toBe(1);
    });

    it('should handle single leaf tree (empty proof)', () => {
      const tree = new MerkleTree(['single']);
      
      const proof = tree.getProof(0);
      
      expect(proof).toEqual([]);
    });
  });

  describe('Proof Verification', () => {
    it('should verify valid proof for leaf', () => {
      const data = ['data1', 'data2', 'data3', 'data4'];
      const tree = new MerkleTree(data);
      const root = tree.getRoot();
      
      // Get proof for index 0
      const proof = tree.getProof(0);
      const leafHash = MerkleTree.hashEventData(data[0]);
      
      const isValid = MerkleTree.verify(leafHash, proof, root);
      
      expect(isValid).toBe(true);
    });

    it('should reject invalid proof (wrong leaf)', () => {
      const data = ['data1', 'data2', 'data3', 'data4'];
      const tree = new MerkleTree(data);
      const root = tree.getRoot();
      
      const proof = tree.getProof(0);
      const wrongLeafHash = MerkleTree.hashEventData('wrongdata');
      
      const isValid = MerkleTree.verify(wrongLeafHash, proof, root);
      
      expect(isValid).toBe(false);
    });

    it('should reject invalid proof (wrong root)', () => {
      const data = ['data1', 'data2'];
      const tree = new MerkleTree(data);
      
      const proof = tree.getProof(0);
      const leafHash = MerkleTree.hashEventData(data[0]);
      const wrongRoot = '0x' + 'a'.repeat(64);
      
      const isValid = MerkleTree.verify(leafHash, proof, wrongRoot);
      
      expect(isValid).toBe(false);
    });

    it('should verify all leaves in tree', () => {
      const data = ['a', 'b', 'c', 'd', 'e'];
      const tree = new MerkleTree(data);
      const root = tree.getRoot();
      
      for (let i = 0; i < data.length; i++) {
        const proof = tree.getProof(i);
        const leafHash = MerkleTree.hashEventData(data[i]);
        
        expect(MerkleTree.verify(leafHash, proof, root)).toBe(true);
      }
    });

    it('should handle case-insensitive root comparison', () => {
      const data = ['test'];
      const tree = new MerkleTree(data);
      const root = tree.getRoot();
      
      const proof = tree.getProof(0);
      const leafHash = MerkleTree.hashEventData(data[0]);
      
      // Test with uppercase root
      const isValid = MerkleTree.verify(leafHash, proof, root.toUpperCase() as `0x${string}`);
      
      expect(isValid).toBe(true);
    });
  });

  describe('Hash Event Data', () => {
    it('should produce keccak256 hash', () => {
      const data = 'test event data';
      const hash = MerkleTree.hashEventData(data);
      
      expect(hash).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should produce consistent hash', () => {
      const data = 'consistent';
      
      const hash1 = MerkleTree.hashEventData(data);
      const hash2 = MerkleTree.hashEventData(data);
      
      expect(hash1).toBe(hash2);
    });

    it('should produce valid keccak256 hash format', () => {
      const data = 'test';
      const hash = MerkleTree.hashEventData(data);
      
      // keccak256 produces 32 bytes = 64 hex chars
      expect(hash).toMatch(/^0x[a-f0-9]{64}$/);
      // Verify it's deterministic
      expect(hash).toBe(MerkleTree.hashEventData(data));
    });
  });
});

// ============================================================================
// BATCH ANCHORING SERVICE TESTS
// ============================================================================

describe('BatchAnchoringService', () => {
  let service: BatchAnchoringService;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    
    // Reset mock
    mockBlockchainService.isEnabled.mockReturnValue(true);
    mockBlockchainService.anchorBatchRoot.mockResolvedValue('0xmocktxhash');
    
    service = new BatchAnchoringService({
      maxBatchSize: 10,
      maxBatchAgeMs: 60000,
      enabled: true,
    });
  });

  afterEach(() => {
    service.shutdown();
    vi.useRealTimers();
  });

  describe('Initialization', () => {
    it('should initialize with default config', () => {
      const config = service.getConfig();
      
      expect(config.maxBatchSize).toBe(10);
      expect(config.maxBatchAgeMs).toBe(60000);
      expect(config.enabled).toBe(true);
    });

    it('should initialize with custom config', () => {
      const customService = new BatchAnchoringService({
        maxBatchSize: 50,
        maxBatchAgeMs: 120000,
        enabled: false,
      });
      
      const config = customService.getConfig();
      
      expect(config.maxBatchSize).toBe(50);
      expect(config.maxBatchAgeMs).toBe(120000);
      expect(config.enabled).toBe(false);
      
      customService.shutdown();
    });

    it('should have empty queue on startup', () => {
      expect(service.getPendingEvents()).toHaveLength(0);
    });

    it('should have zero stats on startup', () => {
      const stats = service.getStats();
      
      expect(stats.pendingEvents).toBe(0);
      expect(stats.totalBatchesAnchored).toBe(0);
      expect(stats.totalEventsAnchored).toBe(0);
      expect(stats.lastBatchTime).toBeNull();
      expect(stats.averageEventsPerBatch).toBe(0);
    });
  });

  describe('Config Updates', () => {
    it('should update config', () => {
      service.updateConfig({ maxBatchSize: 25 });
      
      expect(service.getConfig().maxBatchSize).toBe(25);
    });

    it('should enable/disable service', () => {
      service.updateConfig({ enabled: false });
      
      expect(service.getConfig().enabled).toBe(false);
      
      const result = service.queueEvent(createTestEvent('1'));
      expect(result.queued).toBe(false);
    });

    it('should restart timer on config update when enabled', () => {
      service.updateConfig({ maxBatchAgeMs: 30000 });
      
      // Timer should be restarted - service still works
      service.queueEvent(createTestEvent('1'));
      expect(service.getPendingEvents()).toHaveLength(1);
    });
  });

  describe('Event Queueing', () => {
    it('should queue single event', () => {
      const event = createTestEvent('1');
      
      const result = service.queueEvent(event);
      
      expect(result.queued).toBe(true);
      expect(result.position).toBe(1);
      expect(service.getPendingEvents()).toHaveLength(1);
    });

    it('should queue multiple events', () => {
      const events = generateEvents(5);
      
      events.forEach((e, i) => {
        const result = service.queueEvent(e);
        expect(result.position).toBe(i + 1);
      });
      
      expect(service.getPendingEvents()).toHaveLength(5);
    });

    it('should update pending count in stats', () => {
      service.queueEvent(createTestEvent('1'));
      service.queueEvent(createTestEvent('2'));
      
      expect(service.getStats().pendingEvents).toBe(2);
    });

    it('should not queue when disabled', () => {
      service.updateConfig({ enabled: false });
      
      const result = service.queueEvent(createTestEvent('1'));
      
      expect(result.queued).toBe(false);
      expect(result.position).toBe(-1);
    });

    it('should trigger batch on maxBatchSize', async () => {
      const events = generateEvents(10);
      
      events.forEach(e => service.queueEvent(e));
      
      // Wait for async batch flush
      await vi.runAllTimersAsync();
      
      expect(service.getPendingEvents()).toHaveLength(0);
      expect(service.getStats().totalBatchesAnchored).toBe(1);
      expect(service.getStats().totalEventsAnchored).toBe(10);
    });
  });

  describe('Batch Flushing', () => {
    it('should return null for empty queue', async () => {
      const result = await service.forceBatch();
      
      expect(result).toBeNull();
    });

    it('should flush pending events', async () => {
      service.queueEvent(createTestEvent('1'));
      service.queueEvent(createTestEvent('2'));
      
      const result = await service.forceBatch();
      
      expect(result).not.toBeNull();
      expect(result?.eventCount).toBe(2);
      expect(service.getPendingEvents()).toHaveLength(0);
    });

    it('should generate merkle root', async () => {
      service.queueEvent(createTestEvent('1'));
      
      const result = await service.forceBatch();
      
      expect(result?.merkleRoot).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should generate batch ID', async () => {
      service.queueEvent(createTestEvent('1'));
      
      const result = await service.forceBatch();
      
      expect(result?.batchId).toBeDefined();
      expect(result?.batchId.length).toBe(16);
    });

    it('should call blockchain service when enabled', async () => {
      service.queueEvent(createTestEvent('1'));
      
      await service.forceBatch();
      
      expect(mockBlockchainService.anchorBatchRoot).toHaveBeenCalled();
    });

    it('should include tx hash in result', async () => {
      service.queueEvent(createTestEvent('1'));
      
      const result = await service.forceBatch();
      
      expect(result?.txHash).toBe('0xmocktxhash');
    });

    it('should handle blockchain errors gracefully', async () => {
      mockBlockchainService.anchorBatchRoot.mockRejectedValue(new Error('RPC error'));
      
      service.queueEvent(createTestEvent('1'));
      
      const result = await service.forceBatch();
      
      // Batch still processed, just no tx hash
      expect(result).not.toBeNull();
      expect(result?.txHash).toBeNull();
    });

    it('should not call blockchain when disabled', async () => {
      mockBlockchainService.isEnabled.mockReturnValue(false);
      
      service.queueEvent(createTestEvent('1'));
      
      await service.forceBatch();
      
      expect(mockBlockchainService.anchorBatchRoot).not.toHaveBeenCalled();
    });
  });

  describe('Timer-Based Batching', () => {
    it('should flush on timer expiry', async () => {
      service.queueEvent(createTestEvent('1'));
      
      expect(service.getPendingEvents()).toHaveLength(1);
      
      // Advance timer past maxBatchAgeMs
      await vi.advanceTimersByTimeAsync(60001);
      
      expect(service.getPendingEvents()).toHaveLength(0);
      expect(service.getStats().totalBatchesAnchored).toBe(1);
    });

    it('should not flush empty queue on timer', async () => {
      // No events queued
      await vi.advanceTimersByTimeAsync(60001);
      
      expect(service.getStats().totalBatchesAnchored).toBe(0);
    });
  });

  describe('Statistics Tracking', () => {
    it('should track total batches anchored', async () => {
      service.queueEvent(createTestEvent('1'));
      await service.forceBatch();
      
      service.queueEvent(createTestEvent('2'));
      await service.forceBatch();
      
      expect(service.getStats().totalBatchesAnchored).toBe(2);
    });

    it('should track total events anchored', async () => {
      generateEvents(5).forEach(e => service.queueEvent(e));
      await service.forceBatch();
      
      generateEvents(3).forEach(e => service.queueEvent(e));
      await service.forceBatch();
      
      expect(service.getStats().totalEventsAnchored).toBe(8);
    });

    it('should track last batch time', async () => {
      expect(service.getStats().lastBatchTime).toBeNull();
      
      service.queueEvent(createTestEvent('1'));
      await service.forceBatch();
      
      expect(service.getStats().lastBatchTime).not.toBeNull();
    });

    it('should calculate average events per batch', async () => {
      generateEvents(6).forEach(e => service.queueEvent(e));
      await service.forceBatch();
      
      generateEvents(4).forEach(e => service.queueEvent(e));
      await service.forceBatch();
      
      expect(service.getStats().averageEventsPerBatch).toBe(5);
    });

    it('should estimate gas savings', async () => {
      generateEvents(5).forEach(e => service.queueEvent(e));
      await service.forceBatch();
      
      const savings = service.getStats().estimatedGasSavings;
      
      // 5 events * 50000 individual gas - 70000 batch gas = 180000 saved
      expect(savings).toBe(180000);
    });
  });

  describe('Batch History', () => {
    it('should store batch history', async () => {
      service.queueEvent(createTestEvent('1'));
      await service.forceBatch();
      
      expect(service.getBatchHistory()).toHaveLength(1);
    });

    it('should limit history to 100 batches', async () => {
      for (let i = 0; i < 105; i++) {
        service.queueEvent(createTestEvent(`${i}`));
        await service.forceBatch();
      }
      
      expect(service.getBatchHistory()).toHaveLength(100);
    });

    it('should remove oldest batch when over limit', async () => {
      for (let i = 0; i < 101; i++) {
        service.queueEvent(createTestEvent(`event-${i}`));
        await service.forceBatch();
      }
      
      const history = service.getBatchHistory();
      
      // First batch should be gone
      expect(history[0].events[0].id).toBe('event-1');
    });
  });

  describe('Event Proof Retrieval', () => {
    it('should return null for non-existent batch', () => {
      const result = service.getProofForEvent('nonexistent', 'event-1');
      
      expect(result).toBeNull();
    });

    it('should return null for non-existent event', async () => {
      service.queueEvent(createTestEvent('1'));
      const batch = await service.forceBatch();
      
      const result = service.getProofForEvent(batch!.batchId, 'nonexistent');
      
      expect(result).toBeNull();
    });

    it('should return valid proof for event', async () => {
      const event1 = createTestEvent('1');
      const event2 = createTestEvent('2');
      
      service.queueEvent(event1);
      service.queueEvent(event2);
      
      const batch = await service.forceBatch();
      const result = service.getProofForEvent(batch!.batchId, '1');
      
      expect(result).not.toBeNull();
      expect(result?.root).toBe(batch?.merkleRoot);
      expect(result?.proof).toBeInstanceOf(Array);
      expect(result?.eventHash).toMatch(/^0x[a-f0-9]{64}$/);
    });

    it('should verify event inclusion with proof', async () => {
      const events = generateEvents(4);
      events.forEach(e => service.queueEvent(e));
      
      const batch = await service.forceBatch();
      const result = service.getProofForEvent(batch!.batchId, 'event-2');
      
      expect(result).not.toBeNull();
      
      // Verify the proof is valid
      const isValid = MerkleTree.verify(result!.eventHash, result!.proof, result!.root);
      expect(isValid).toBe(true);
    });
  });

  describe('Shutdown', () => {
    it('should flush remaining events on shutdown', async () => {
      const newService = new BatchAnchoringService({
        maxBatchSize: 100,
        maxBatchAgeMs: 300000,
        enabled: true,
      });
      
      newService.queueEvent(createTestEvent('1'));
      newService.queueEvent(createTestEvent('2'));
      
      expect(newService.getPendingEvents()).toHaveLength(2);
      
      // Shutdown triggers flush
      newService.shutdown();
      
      // Events should be flushed
      expect(newService.getStats().totalBatchesAnchored).toBe(1);
    });

    it('should not flush if queue is empty', () => {
      const newService = new BatchAnchoringService({ enabled: true });
      
      newService.shutdown();
      
      expect(newService.getStats().totalBatchesAnchored).toBe(0);
    });
  });
});

// ============================================================================
// INTEGRATION TESTS
// ============================================================================

describe('Batch Anchoring Integration', () => {
  let service: BatchAnchoringService;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    mockBlockchainService.isEnabled.mockReturnValue(true);
    mockBlockchainService.anchorBatchRoot.mockResolvedValue('0xintegrationtx');
    
    service = new BatchAnchoringService({
      maxBatchSize: 5,
      maxBatchAgeMs: 10000,
      enabled: true,
    });
  });

  afterEach(() => {
    service.shutdown();
    vi.useRealTimers();
  });

  it('should complete full event → batch → anchor → verify flow', async () => {
    // 1. Queue events
    const events = generateEvents(3);
    events.forEach(e => service.queueEvent(e));
    
    // 2. Force batch creation
    const batch = await service.forceBatch();
    
    expect(batch).not.toBeNull();
    expect(batch!.eventCount).toBe(3);
    expect(batch!.merkleRoot).toBeDefined();
    expect(batch!.txHash).toBe('0xintegrationtx');
    
    // 3. Verify event inclusion
    for (const event of events) {
      const proof = service.getProofForEvent(batch!.batchId, event.id);
      expect(proof).not.toBeNull();
      expect(MerkleTree.verify(proof!.eventHash, proof!.proof, proof!.root)).toBe(true);
    }
    
    // 4. Check stats
    const stats = service.getStats();
    expect(stats.totalBatchesAnchored).toBe(1);
    expect(stats.totalEventsAnchored).toBe(3);
  });

  it('should handle mixed trigger modes (size and timer)', async () => {
    // Trigger by size (5 events)
    generateEvents(5).forEach(e => service.queueEvent(e));
    await vi.runAllTimersAsync();
    
    expect(service.getStats().totalBatchesAnchored).toBe(1);
    
    // Add more events but not enough to trigger
    service.queueEvent(createTestEvent('extra-1'));
    service.queueEvent(createTestEvent('extra-2'));
    
    expect(service.getPendingEvents()).toHaveLength(2);
    
    // Trigger by timer
    await vi.advanceTimersByTimeAsync(10001);
    
    expect(service.getStats().totalBatchesAnchored).toBe(2);
    expect(service.getStats().totalEventsAnchored).toBe(7);
  });

  it('should handle high-volume event stream', async () => {
    const eventCount = 50;
    const events = generateEvents(eventCount);
    
    events.forEach(e => service.queueEvent(e));
    await vi.runAllTimersAsync();
    
    const stats = service.getStats();
    
    // 50 events / 5 per batch = 10 batches
    expect(stats.totalBatchesAnchored).toBe(10);
    expect(stats.totalEventsAnchored).toBe(50);
    expect(stats.averageEventsPerBatch).toBe(5);
  });

  it('should handle concurrent event sources', async () => {
    // Simulate multiple sources adding events
    const source1Events = [
      createTestEvent('s1-1', { eventType: 'ALARM' }),
      createTestEvent('s1-2', { eventType: 'ALARM' }),
    ];
    
    const source2Events = [
      createTestEvent('s2-1', { eventType: 'READING' }),
      createTestEvent('s2-2', { eventType: 'READING' }),
      createTestEvent('s2-3', { eventType: 'READING' }),
    ];
    
    // Interleave events
    service.queueEvent(source1Events[0]);
    service.queueEvent(source2Events[0]);
    service.queueEvent(source1Events[1]);
    service.queueEvent(source2Events[1]);
    service.queueEvent(source2Events[2]);
    
    await vi.runAllTimersAsync();
    
    const history = service.getBatchHistory();
    expect(history).toHaveLength(1);
    expect(history[0].eventCount).toBe(5);
    
    // All events should be verifiable
    [...source1Events, ...source2Events].forEach(event => {
      const proof = service.getProofForEvent(history[0].batchId, event.id);
      expect(proof).not.toBeNull();
    });
  });

  it('should maintain data integrity across multiple batches', async () => {
    const allEvents: BatchableEvent[] = [];
    
    // Create multiple batches
    for (let batch = 0; batch < 3; batch++) {
      const events = generateEvents(5).map(e => ({
        ...e,
        id: `batch${batch}-${e.id}`,
      }));
      
      allEvents.push(...events);
      events.forEach(e => service.queueEvent(e));
    }
    
    await vi.runAllTimersAsync();
    
    const history = service.getBatchHistory();
    expect(history).toHaveLength(3);
    
    // Verify each event in its correct batch
    history.forEach((batch, batchIdx) => {
      batch.events.forEach(event => {
        expect(event.id).toContain(`batch${batchIdx}`);
        
        const proof = service.getProofForEvent(batch.batchId, event.id);
        expect(proof).not.toBeNull();
        expect(MerkleTree.verify(proof!.eventHash, proof!.proof, batch.merkleRoot)).toBe(true);
      });
    });
  });

  it('should handle network failures with retry capability', async () => {
    // First call fails
    mockBlockchainService.anchorBatchRoot
      .mockRejectedValueOnce(new Error('Network timeout'))
      .mockResolvedValue('0xretry-success');
    
    service.queueEvent(createTestEvent('1'));
    const result1 = await service.forceBatch();
    
    expect(result1?.txHash).toBeNull(); // First batch failed to anchor
    
    // Retry mechanism would be at application level
    // But batch is still recorded locally
    expect(service.getBatchHistory()).toHaveLength(1);
  });
});

// ============================================================================
// EDGE CASE TESTS
// ============================================================================

describe('Edge Cases', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    mockBlockchainService.isEnabled.mockReturnValue(true);
    mockBlockchainService.anchorBatchRoot.mockResolvedValue('0xedge');
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('should handle events with special characters in payload', async () => {
    const service = new BatchAnchoringService({ enabled: true, maxBatchSize: 5 });
    
    const event = createTestEvent('special', {
      payload: {
        message: 'Test with "quotes" and \'apostrophes\'',
        unicode: '日本語テスト',
        emoji: '🔥💧⚡',
      },
    });
    
    service.queueEvent(event);
    const result = await service.forceBatch();
    
    expect(result).not.toBeNull();
    expect(result?.merkleRoot).toBeDefined();
    
    service.shutdown();
  });

  it('should handle events with very large payloads', async () => {
    const service = new BatchAnchoringService({ enabled: true, maxBatchSize: 5 });
    
    const largePayload = {
      data: 'x'.repeat(100000), // 100KB payload
      nested: {
        array: Array(1000).fill({ value: Math.random() }),
      },
    };
    
    const event = createTestEvent('large', { payload: largePayload });
    
    service.queueEvent(event);
    const result = await service.forceBatch();
    
    expect(result).not.toBeNull();
    expect(result?.eventCount).toBe(1);
    
    service.shutdown();
  });

  it('should handle timestamp edge cases', async () => {
    const service = new BatchAnchoringService({ enabled: true, maxBatchSize: 5 });
    
    const oldDate = new Date('2000-01-01T00:00:00Z');
    const futureDate = new Date('2100-01-01T00:00:00Z');
    
    service.queueEvent(createTestEvent('past', { timestamp: oldDate }));
    service.queueEvent(createTestEvent('future', { timestamp: futureDate }));
    
    const result = await service.forceBatch();
    
    expect(result?.eventCount).toBe(2);
    
    service.shutdown();
  });

  it('should handle rapid enable/disable cycles', async () => {
    const service = new BatchAnchoringService({ enabled: true, maxBatchSize: 10 });
    
    service.queueEvent(createTestEvent('1'));
    service.updateConfig({ enabled: false });
    
    const result1 = service.queueEvent(createTestEvent('2'));
    expect(result1.queued).toBe(false);
    
    service.updateConfig({ enabled: true });
    
    const result2 = service.queueEvent(createTestEvent('3'));
    expect(result2.queued).toBe(true);
    
    expect(service.getPendingEvents()).toHaveLength(2);
    
    service.shutdown();
  });

  it('should handle zero maxBatchAgeMs (immediate timer trigger)', async () => {
    const service = new BatchAnchoringService({
      enabled: true,
      maxBatchSize: 100,
      maxBatchAgeMs: 1, // Very short
    });
    
    service.queueEvent(createTestEvent('1'));
    
    await vi.advanceTimersByTimeAsync(5);
    
    expect(service.getStats().totalBatchesAnchored).toBe(1);
    
    service.shutdown();
  });
});
