/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * 0xSCADA Artifact Capture Infrastructure
 *
 * Copyright (c) 2024 0xSCADA Project
 */

#ifndef _SCADA_ARTIFACT_H
#define _SCADA_ARTIFACT_H

#include <linux/types.h>
#include <linux/time64.h>
#include <linux/list.h>
#include <linux/kref.h>
#include <linux/crypto.h>

#define SCADA_ARTIFACT_VERSION	"1.0.0"
#define SCADA_HASH_SIZE		32	/* SHA-256 */
#define SCADA_SUMMARY_MAX	500
#define SCADA_MAX_DEPENDENCIES	16

/**
 * enum scada_origin_type - Source of the artifact
 * @SCADA_ORIGIN_SYSTEM: Generated by kernel/hardware
 * @SCADA_ORIGIN_AGENT: Generated by autonomous agent
 * @SCADA_ORIGIN_FORK: Generated by a 0xSCADA fork
 */
enum scada_origin_type {
	SCADA_ORIGIN_SYSTEM = 0,
	SCADA_ORIGIN_AGENT,
	SCADA_ORIGIN_FORK,
};

/**
 * enum scada_scope - Domain of the artifact
 * @SCADA_SCOPE_LINUX: Kernel traces, syscalls, hardware
 * @SCADA_SCOPE_ETHEREUM: Proofs, state diffs, ZK
 * @SCADA_SCOPE_AGENTIC: Agent reasoning, embeddings
 * @SCADA_SCOPE_CROSS: Spans multiple domains
 */
enum scada_scope {
	SCADA_SCOPE_LINUX = 0,
	SCADA_SCOPE_ETHEREUM,
	SCADA_SCOPE_AGENTIC,
	SCADA_SCOPE_CROSS,
};

/**
 * enum scada_content_type - Type of artifact content
 * @SCADA_CONTENT_TRACE: Execution trace
 * @SCADA_CONTENT_PROOF: Cryptographic proof
 * @SCADA_CONTENT_WITNESS: Proof witness data
 * @SCADA_CONTENT_SNAPSHOT: Point-in-time state
 * @SCADA_CONTENT_TWIN: Digital twin data
 */
enum scada_content_type {
	SCADA_CONTENT_TRACE = 0,
	SCADA_CONTENT_PROOF,
	SCADA_CONTENT_WITNESS,
	SCADA_CONTENT_SNAPSHOT,
	SCADA_CONTENT_TWIN,
};

/**
 * enum scada_dep_relationship - Dependency relationship type
 * @SCADA_DEP_REQUIRES: Must exist for validity
 * @SCADA_DEP_EXTENDS: Builds upon
 * @SCADA_DEP_SUPERSEDES: Replaces
 * @SCADA_DEP_REFERENCES: Informational only
 */
enum scada_dep_relationship {
	SCADA_DEP_REQUIRES = 0,
	SCADA_DEP_EXTENDS,
	SCADA_DEP_SUPERSEDES,
	SCADA_DEP_REFERENCES,
};

/**
 * struct scada_dependency - Artifact dependency
 * @hash: SHA-256 hash of the dependency
 * @relationship: Type of dependency relationship
 */
struct scada_dependency {
	u8 hash[SCADA_HASH_SIZE];
	enum scada_dep_relationship relationship;
};

/**
 * struct scada_artifact - Reality artifact
 * @id: Content-addressed SHA-256 hash (computed on finalize)
 * @timestamp: Nanosecond timestamp of creation
 * @origin_type: Source type (system/agent/fork)
 * @origin_id: Identifier of the origin
 * @scope: Domain scope
 * @content_type: Type of content
 * @content: Pointer to content data
 * @content_size: Size of content in bytes
 * @content_hash: SHA-256 of content (for verification)
 * @summary: Human-readable description
 * @dependencies: Array of dependencies
 * @num_dependencies: Number of dependencies
 * @finalized: True if artifact is immutable
 * @refcount: Reference counter
 * @list: List linkage for artifact chains
 */
struct scada_artifact {
	u8 id[SCADA_HASH_SIZE];
	u64 timestamp;
	
	enum scada_origin_type origin_type;
	char origin_id[64];
	
	enum scada_scope scope;
	char subsystem[32];
	
	enum scada_content_type content_type;
	void *content;
	size_t content_size;
	u8 content_hash[SCADA_HASH_SIZE];
	
	char summary[SCADA_SUMMARY_MAX];
	
	struct scada_dependency dependencies[SCADA_MAX_DEPENDENCIES];
	unsigned int num_dependencies;
	
	bool finalized;
	struct kref refcount;
	struct list_head list;
};

/* Lifecycle management */
struct scada_artifact *scada_artifact_create(enum scada_origin_type origin,
					     enum scada_scope scope);
void scada_artifact_destroy(struct scada_artifact *art);
struct scada_artifact *scada_artifact_get(struct scada_artifact *art);
void scada_artifact_put(struct scada_artifact *art);

/* Configuration (before finalize) */
int scada_artifact_set_origin_id(struct scada_artifact *art, const char *id);
int scada_artifact_set_subsystem(struct scada_artifact *art, const char *subsys);
int scada_artifact_set_content_type(struct scada_artifact *art,
				    enum scada_content_type type);
int scada_artifact_set_content(struct scada_artifact *art,
			       const void *data, size_t len);
int scada_artifact_set_summary(struct scada_artifact *art, const char *summary);
int scada_artifact_add_dependency(struct scada_artifact *art,
				  const u8 *hash,
				  enum scada_dep_relationship rel);

/* Finalization */
int scada_artifact_finalize(struct scada_artifact *art);
bool scada_artifact_is_finalized(const struct scada_artifact *art);

/* Verification */
int scada_artifact_verify(const struct scada_artifact *art);
int scada_artifact_verify_content(const struct scada_artifact *art);
int scada_artifact_verify_id(const struct scada_artifact *art);

/* Accessors */
const u8 *scada_artifact_get_id(const struct scada_artifact *art);
u64 scada_artifact_get_timestamp(const struct scada_artifact *art);
const char *scada_artifact_get_summary(const struct scada_artifact *art);

/* Serialization */
ssize_t scada_artifact_serialize(const struct scada_artifact *art,
				 void *buf, size_t len);
struct scada_artifact *scada_artifact_deserialize(const void *buf, size_t len);

/* Hash utilities */
int scada_hash_data(const void *data, size_t len, u8 *out);
void scada_hash_to_hex(const u8 *hash, char *hex, size_t hex_len);
int scada_hex_to_hash(const char *hex, u8 *hash);

/* Debug */
void scada_artifact_dump(const struct scada_artifact *art);

#endif /* _SCADA_ARTIFACT_H */
