apiVersion: v1
kind: Service
metadata:
  name: modbus-driver
  namespace: oxscada-protocols
  labels:
    app.kubernetes.io/name: modbus-driver
    app.kubernetes.io/part-of: oxscada
spec:
  type: ClusterIP
  ports:
    - port: 5020
      targetPort: 5020
      name: http
  selector:
    app.kubernetes.io/name: modbus-driver
