/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ChangeIntentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvals"
      | "approveIntent"
      | "createIntent"
      | "getApproval"
      | "getIntent"
      | "getIntentApproverCount"
      | "getIntentCount"
      | "getSiteIntentCount"
      | "intentApprovers"
      | "intentIds"
      | "intents"
      | "isFullyApproved"
      | "markDeployed"
      | "markRolledBack"
      | "rejectIntent"
      | "siteIntents"
      | "siteRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IntentApproved"
      | "IntentCreated"
      | "IntentDeployed"
      | "IntentRejected"
      | "IntentRolledBack"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvals",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveIntent",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproval",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentApproverCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSiteIntentCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intentApprovers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "intentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "intents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isFullyApproved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markDeployed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markRolledBack",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectIntent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "siteIntents",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "siteRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntentApproverCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIntentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSiteIntentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intentApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "intentIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFullyApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markRolledBack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "siteIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "siteRegistry",
    data: BytesLike
  ): Result;
}

export namespace IntentApprovedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    approver: AddressLike,
    approvalCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    approver: string,
    approvalCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    approver: string;
    approvalCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    siteId: BytesLike,
    blueprintHash: BytesLike,
    codeHash: BytesLike,
    requiredApprovals: BigNumberish,
    createdBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    siteId: string,
    blueprintHash: string,
    codeHash: string,
    requiredApprovals: bigint,
    createdBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    siteId: string;
    blueprintHash: string;
    codeHash: string;
    requiredApprovals: bigint;
    createdBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentDeployedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    deployedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    deployedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    deployedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentRejectedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    rejectedBy: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    rejectedBy: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    rejectedBy: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentRolledBackEvent {
  export type InputTuple = [
    intentId: BytesLike,
    rolledBackBy: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    rolledBackBy: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    intentId: string;
    rolledBackBy: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChangeIntent extends BaseContract {
  connect(runner?: ContractRunner | null): ChangeIntent;
  waitForDeployment(): Promise<this>;

  interface: ChangeIntentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvals: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, string, string, bigint] & {
        approver: string;
        signatureHash: string;
        comment: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;

  approveIntent: TypedContractMethod<
    [intentId: BytesLike, signatureHash: BytesLike, comment: string],
    [void],
    "nonpayable"
  >;

  createIntent: TypedContractMethod<
    [
      siteId: BytesLike,
      blueprintHash: BytesLike,
      codeHash: BytesLike,
      changePackageHash: BytesLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getApproval: TypedContractMethod<
    [intentId: BytesLike, approver: AddressLike],
    [
      [string, string, bigint] & {
        signatureHash: string;
        comment: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;

  getIntent: TypedContractMethod<
    [intentId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        siteId: string;
        blueprintHash: string;
        codeHash: string;
        changePackageHash: string;
        requiredApprovals: bigint;
        approvalCount: bigint;
        status: bigint;
        createdAt: bigint;
        approvedAt: bigint;
        deployedAt: bigint;
        createdBy: string;
        deployedBy: string;
      }
    ],
    "view"
  >;

  getIntentApproverCount: TypedContractMethod<
    [intentId: BytesLike],
    [bigint],
    "view"
  >;

  getIntentCount: TypedContractMethod<[], [bigint], "view">;

  getSiteIntentCount: TypedContractMethod<
    [siteId: BytesLike],
    [bigint],
    "view"
  >;

  intentApprovers: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  intentIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  intents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        siteId: string;
        blueprintHash: string;
        codeHash: string;
        changePackageHash: string;
        requiredApprovals: bigint;
        approvalCount: bigint;
        status: bigint;
        createdAt: bigint;
        approvedAt: bigint;
        deployedAt: bigint;
        createdBy: string;
        deployedBy: string;
      }
    ],
    "view"
  >;

  isFullyApproved: TypedContractMethod<
    [intentId: BytesLike],
    [boolean],
    "view"
  >;

  markDeployed: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  markRolledBack: TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  rejectIntent: TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  siteIntents: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  siteRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, string, string, bigint] & {
        approver: string;
        signatureHash: string;
        comment: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, signatureHash: BytesLike, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<
    [
      siteId: BytesLike,
      blueprintHash: BytesLike,
      codeHash: BytesLike,
      changePackageHash: BytesLike,
      requiredApprovals: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproval"
  ): TypedContractMethod<
    [intentId: BytesLike, approver: AddressLike],
    [
      [string, string, bigint] & {
        signatureHash: string;
        comment: string;
        approvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        siteId: string;
        blueprintHash: string;
        codeHash: string;
        changePackageHash: string;
        requiredApprovals: bigint;
        approvalCount: bigint;
        status: bigint;
        createdAt: bigint;
        approvedAt: bigint;
        deployedAt: bigint;
        createdBy: string;
        deployedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIntentApproverCount"
  ): TypedContractMethod<[intentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getIntentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSiteIntentCount"
  ): TypedContractMethod<[siteId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "intentApprovers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "intentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        siteId: string;
        blueprintHash: string;
        codeHash: string;
        changePackageHash: string;
        requiredApprovals: bigint;
        approvalCount: bigint;
        status: bigint;
        createdAt: bigint;
        approvedAt: bigint;
        deployedAt: bigint;
        createdBy: string;
        deployedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFullyApproved"
  ): TypedContractMethod<[intentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markDeployed"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markRolledBack"
  ): TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "siteIntents"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "siteRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "IntentApproved"
  ): TypedContractEvent<
    IntentApprovedEvent.InputTuple,
    IntentApprovedEvent.OutputTuple,
    IntentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "IntentCreated"
  ): TypedContractEvent<
    IntentCreatedEvent.InputTuple,
    IntentCreatedEvent.OutputTuple,
    IntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IntentDeployed"
  ): TypedContractEvent<
    IntentDeployedEvent.InputTuple,
    IntentDeployedEvent.OutputTuple,
    IntentDeployedEvent.OutputObject
  >;
  getEvent(
    key: "IntentRejected"
  ): TypedContractEvent<
    IntentRejectedEvent.InputTuple,
    IntentRejectedEvent.OutputTuple,
    IntentRejectedEvent.OutputObject
  >;
  getEvent(
    key: "IntentRolledBack"
  ): TypedContractEvent<
    IntentRolledBackEvent.InputTuple,
    IntentRolledBackEvent.OutputTuple,
    IntentRolledBackEvent.OutputObject
  >;

  filters: {
    "IntentApproved(bytes32,address,uint256,uint256)": TypedContractEvent<
      IntentApprovedEvent.InputTuple,
      IntentApprovedEvent.OutputTuple,
      IntentApprovedEvent.OutputObject
    >;
    IntentApproved: TypedContractEvent<
      IntentApprovedEvent.InputTuple,
      IntentApprovedEvent.OutputTuple,
      IntentApprovedEvent.OutputObject
    >;

    "IntentCreated(bytes32,bytes32,bytes32,bytes32,uint256,address,uint256)": TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;
    IntentCreated: TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;

    "IntentDeployed(bytes32,address,uint256)": TypedContractEvent<
      IntentDeployedEvent.InputTuple,
      IntentDeployedEvent.OutputTuple,
      IntentDeployedEvent.OutputObject
    >;
    IntentDeployed: TypedContractEvent<
      IntentDeployedEvent.InputTuple,
      IntentDeployedEvent.OutputTuple,
      IntentDeployedEvent.OutputObject
    >;

    "IntentRejected(bytes32,address,string,uint256)": TypedContractEvent<
      IntentRejectedEvent.InputTuple,
      IntentRejectedEvent.OutputTuple,
      IntentRejectedEvent.OutputObject
    >;
    IntentRejected: TypedContractEvent<
      IntentRejectedEvent.InputTuple,
      IntentRejectedEvent.OutputTuple,
      IntentRejectedEvent.OutputObject
    >;

    "IntentRolledBack(bytes32,address,string,uint256)": TypedContractEvent<
      IntentRolledBackEvent.InputTuple,
      IntentRolledBackEvent.OutputTuple,
      IntentRolledBackEvent.OutputObject
    >;
    IntentRolledBack: TypedContractEvent<
      IntentRolledBackEvent.InputTuple,
      IntentRolledBackEvent.OutputTuple,
      IntentRolledBackEvent.OutputObject
    >;
  };
}
