/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EventAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorBatch"
      | "anchorIds"
      | "anchors"
      | "getAnchor"
      | "getAnchorCount"
      | "getSiteAnchorAt"
      | "getSiteAnchorCount"
      | "siteAnchors"
      | "siteRegistry"
      | "verifyEvent"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorBatch",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "anchors", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAnchor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSiteAnchorAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSiteAnchorCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "siteAnchors",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "siteRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvent",
    values: [BytesLike, BytesLike, BytesLike[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchorIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAnchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSiteAnchorAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSiteAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "siteAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "siteRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvent",
    data: BytesLike
  ): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    anchorId: BytesLike,
    siteId: BytesLike,
    merkleRoot: BytesLike,
    eventCount: BigNumberish,
    timestamp: BigNumberish,
    anchoredBy: AddressLike
  ];
  export type OutputTuple = [
    anchorId: string,
    siteId: string,
    merkleRoot: string,
    eventCount: bigint,
    timestamp: bigint,
    anchoredBy: string
  ];
  export interface OutputObject {
    anchorId: string;
    siteId: string;
    merkleRoot: string;
    eventCount: bigint;
    timestamp: bigint;
    anchoredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): EventAnchor;
  waitForDeployment(): Promise<this>;

  interface: EventAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorBatch: TypedContractMethod<
    [
      siteId: BytesLike,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      metadataUri: string,
      eventCount: BigNumberish,
      firstEventTimestamp: BigNumberish,
      lastEventTimestamp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  anchorIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  anchors: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        siteId: string;
        merkleRoot: string;
        metadataHash: string;
        metadataUri: string;
        eventCount: bigint;
        firstEventTimestamp: bigint;
        lastEventTimestamp: bigint;
        anchoredAt: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;

  getAnchor: TypedContractMethod<
    [anchorId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        siteId: string;
        merkleRoot: string;
        metadataHash: string;
        metadataUri: string;
        eventCount: bigint;
        firstEventTimestamp: bigint;
        lastEventTimestamp: bigint;
        anchoredAt: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;

  getAnchorCount: TypedContractMethod<[], [bigint], "view">;

  getSiteAnchorAt: TypedContractMethod<
    [siteId: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;

  getSiteAnchorCount: TypedContractMethod<
    [siteId: BytesLike],
    [bigint],
    "view"
  >;

  siteAnchors: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  siteRegistry: TypedContractMethod<[], [string], "view">;

  verifyEvent: TypedContractMethod<
    [
      anchorId: BytesLike,
      eventHash: BytesLike,
      proof: BytesLike[],
      index: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorBatch"
  ): TypedContractMethod<
    [
      siteId: BytesLike,
      merkleRoot: BytesLike,
      metadataHash: BytesLike,
      metadataUri: string,
      eventCount: BigNumberish,
      firstEventTimestamp: BigNumberish,
      lastEventTimestamp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "anchors"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        siteId: string;
        merkleRoot: string;
        metadataHash: string;
        metadataUri: string;
        eventCount: bigint;
        firstEventTimestamp: bigint;
        lastEventTimestamp: bigint;
        anchoredAt: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAnchor"
  ): TypedContractMethod<
    [anchorId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        siteId: string;
        merkleRoot: string;
        metadataHash: string;
        metadataUri: string;
        eventCount: bigint;
        firstEventTimestamp: bigint;
        lastEventTimestamp: bigint;
        anchoredAt: bigint;
        anchoredBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAnchorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSiteAnchorAt"
  ): TypedContractMethod<
    [siteId: BytesLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSiteAnchorCount"
  ): TypedContractMethod<[siteId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "siteAnchors"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "siteRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyEvent"
  ): TypedContractMethod<
    [
      anchorId: BytesLike,
      eventHash: BytesLike,
      proof: BytesLike[],
      index: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(bytes32,bytes32,bytes32,uint256,uint256,address)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
  };
}
