/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IndustrialRegistry {
  export type AssetRegistryStruct = {
    siteId: string;
    assetType: string;
    nameOrTag: string;
    critical: boolean;
    registeredAt: BigNumberish;
  };

  export type AssetRegistryStructOutput = [
    siteId: string,
    assetType: string,
    nameOrTag: string,
    critical: boolean,
    registeredAt: bigint
  ] & {
    siteId: string;
    assetType: string;
    nameOrTag: string;
    critical: boolean;
    registeredAt: bigint;
  };

  export type SiteRegistryStruct = {
    name: string;
    location: string;
    owner: AddressLike;
    registeredAt: BigNumberish;
    active: boolean;
  };

  export type SiteRegistryStructOutput = [
    name: string,
    location: string,
    owner: string,
    registeredAt: bigint,
    active: boolean
  ] & {
    name: string;
    location: string;
    owner: string;
    registeredAt: bigint;
    active: boolean;
  };
}

export interface IndustrialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorEvent"
      | "anchorMaintenance"
      | "assetIds"
      | "assets"
      | "getAsset"
      | "getAssetCount"
      | "getSite"
      | "getSiteCount"
      | "registerAsset"
      | "registerSite"
      | "siteIds"
      | "sites"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "EventAnchored"
      | "MaintenanceAnchored"
      | "SiteRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorEvent",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorMaintenance",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "assets", values: [string]): string;
  encodeFunctionData(functionFragment: "getAsset", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAssetCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSite", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getSiteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [string, string, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSite",
    values: [string, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "siteIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sites", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "anchorEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorMaintenance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSiteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "siteIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sites", data: BytesLike): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetId: string,
    siteId: string,
    assetType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    siteId: string,
    assetType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assetId: string;
    siteId: string;
    assetType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventAnchoredEvent {
  export type InputTuple = [
    assetId: string,
    eventType: string,
    payloadHash: BytesLike,
    timestamp: BigNumberish,
    recordedBy: AddressLike
  ];
  export type OutputTuple = [
    assetId: string,
    eventType: string,
    payloadHash: string,
    timestamp: bigint,
    recordedBy: string
  ];
  export interface OutputObject {
    assetId: string;
    eventType: string;
    payloadHash: string;
    timestamp: bigint;
    recordedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaintenanceAnchoredEvent {
  export type InputTuple = [
    assetId: string,
    workOrderId: string,
    maintenanceType: string,
    timestamp: BigNumberish,
    performedBy: AddressLike
  ];
  export type OutputTuple = [
    assetId: string,
    workOrderId: string,
    maintenanceType: string,
    timestamp: bigint,
    performedBy: string
  ];
  export interface OutputObject {
    assetId: string;
    workOrderId: string;
    maintenanceType: string;
    timestamp: bigint;
    performedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteRegisteredEvent {
  export type InputTuple = [
    siteId: string,
    name: string,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    siteId: string,
    name: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    siteId: string;
    name: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IndustrialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IndustrialRegistry;
  waitForDeployment(): Promise<this>;

  interface: IndustrialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorEvent: TypedContractMethod<
    [assetId: string, eventType: string, payloadHash: BytesLike],
    [void],
    "nonpayable"
  >;

  anchorMaintenance: TypedContractMethod<
    [
      assetId: string,
      workOrderId: string,
      maintenanceType: string,
      performedAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  assetIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  assets: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint] & {
        siteId: string;
        assetType: string;
        nameOrTag: string;
        critical: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getAsset: TypedContractMethod<
    [assetId: string],
    [IndustrialRegistry.AssetRegistryStructOutput],
    "view"
  >;

  getAssetCount: TypedContractMethod<[], [bigint], "view">;

  getSite: TypedContractMethod<
    [siteId: string],
    [IndustrialRegistry.SiteRegistryStructOutput],
    "view"
  >;

  getSiteCount: TypedContractMethod<[], [bigint], "view">;

  registerAsset: TypedContractMethod<
    [
      assetId: string,
      siteId: string,
      assetType: string,
      nameOrTag: string,
      critical: boolean
    ],
    [void],
    "nonpayable"
  >;

  registerSite: TypedContractMethod<
    [siteId: string, name: string, location: string, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  siteIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  sites: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        location: string;
        owner: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorEvent"
  ): TypedContractMethod<
    [assetId: string, eventType: string, payloadHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorMaintenance"
  ): TypedContractMethod<
    [
      assetId: string,
      workOrderId: string,
      maintenanceType: string,
      performedAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assetIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, bigint] & {
        siteId: string;
        assetType: string;
        nameOrTag: string;
        critical: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [assetId: string],
    [IndustrialRegistry.AssetRegistryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSite"
  ): TypedContractMethod<
    [siteId: string],
    [IndustrialRegistry.SiteRegistryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSiteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      assetId: string,
      siteId: string,
      assetType: string,
      nameOrTag: string,
      critical: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerSite"
  ): TypedContractMethod<
    [siteId: string, name: string, location: string, owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "siteIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sites"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        location: string;
        owner: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EventAnchored"
  ): TypedContractEvent<
    EventAnchoredEvent.InputTuple,
    EventAnchoredEvent.OutputTuple,
    EventAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "MaintenanceAnchored"
  ): TypedContractEvent<
    MaintenanceAnchoredEvent.InputTuple,
    MaintenanceAnchoredEvent.OutputTuple,
    MaintenanceAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "SiteRegistered"
  ): TypedContractEvent<
    SiteRegisteredEvent.InputTuple,
    SiteRegisteredEvent.OutputTuple,
    SiteRegisteredEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(string,string,string,uint256)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "EventAnchored(string,string,bytes32,uint256,address)": TypedContractEvent<
      EventAnchoredEvent.InputTuple,
      EventAnchoredEvent.OutputTuple,
      EventAnchoredEvent.OutputObject
    >;
    EventAnchored: TypedContractEvent<
      EventAnchoredEvent.InputTuple,
      EventAnchoredEvent.OutputTuple,
      EventAnchoredEvent.OutputObject
    >;

    "MaintenanceAnchored(string,string,string,uint256,address)": TypedContractEvent<
      MaintenanceAnchoredEvent.InputTuple,
      MaintenanceAnchoredEvent.OutputTuple,
      MaintenanceAnchoredEvent.OutputObject
    >;
    MaintenanceAnchored: TypedContractEvent<
      MaintenanceAnchoredEvent.InputTuple,
      MaintenanceAnchoredEvent.OutputTuple,
      MaintenanceAnchoredEvent.OutputObject
    >;

    "SiteRegistered(string,string,address,uint256)": TypedContractEvent<
      SiteRegisteredEvent.InputTuple,
      SiteRegisteredEvent.OutputTuple,
      SiteRegisteredEvent.OutputObject
    >;
    SiteRegistered: TypedContractEvent<
      SiteRegisteredEvent.InputTuple,
      SiteRegisteredEvent.OutputTuple,
      SiteRegisteredEvent.OutputObject
    >;
  };
}
