/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SiteRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeGateway"
      | "authorizeSigner"
      | "authorizedGateways"
      | "authorizedSigners"
      | "deactivateSite"
      | "getSite"
      | "getSiteCount"
      | "isGatewayAuthorized"
      | "isSignerAuthorized"
      | "registerSite"
      | "revokeGateway"
      | "revokeSigner"
      | "siteIds"
      | "sites"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GatewayAuthorized"
      | "GatewayRevoked"
      | "SignerAuthorized"
      | "SignerRevoked"
      | "SiteDeactivated"
      | "SiteOwnershipTransferred"
      | "SiteRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeGateway",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeSigner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedGateways",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedSigners",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateSite",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getSite", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getSiteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGatewayAuthorized",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSignerAuthorized",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSite",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeGateway",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSigner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "siteIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sites", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedGateways",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateSite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSite", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSiteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGatewayAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSignerAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "siteIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sites", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace GatewayAuthorizedEvent {
  export type InputTuple = [
    siteId: BytesLike,
    gateway: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    siteId: string,
    gateway: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    siteId: string;
    gateway: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GatewayRevokedEvent {
  export type InputTuple = [
    siteId: BytesLike,
    gateway: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    siteId: string,
    gateway: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    siteId: string;
    gateway: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAuthorizedEvent {
  export type InputTuple = [
    siteId: BytesLike,
    signer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [siteId: string, signer: string, timestamp: bigint];
  export interface OutputObject {
    siteId: string;
    signer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerRevokedEvent {
  export type InputTuple = [
    siteId: BytesLike,
    signer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [siteId: string, signer: string, timestamp: bigint];
  export interface OutputObject {
    siteId: string;
    signer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteDeactivatedEvent {
  export type InputTuple = [siteId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [siteId: string, timestamp: bigint];
  export interface OutputObject {
    siteId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteOwnershipTransferredEvent {
  export type InputTuple = [
    siteId: BytesLike,
    previousOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    siteId: string,
    previousOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    siteId: string;
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SiteRegisteredEvent {
  export type InputTuple = [
    siteId: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [siteId: string, owner: string, timestamp: bigint];
  export interface OutputObject {
    siteId: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SiteRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SiteRegistry;
  waitForDeployment(): Promise<this>;

  interface: SiteRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeGateway: TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizeSigner: TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedGateways: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  authorizedSigners: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  deactivateSite: TypedContractMethod<
    [siteId: BytesLike],
    [void],
    "nonpayable"
  >;

  getSite: TypedContractMethod<
    [siteId: BytesLike],
    [
      [string, boolean, bigint] & {
        owner: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getSiteCount: TypedContractMethod<[], [bigint], "view">;

  isGatewayAuthorized: TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [boolean],
    "view"
  >;

  isSignerAuthorized: TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;

  registerSite: TypedContractMethod<[siteId: BytesLike], [void], "nonpayable">;

  revokeGateway: TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeSigner: TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [void],
    "nonpayable"
  >;

  siteIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  sites: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        owner: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [siteId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeGateway"
  ): TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeSigner"
  ): TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedGateways"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedSigners"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateSite"
  ): TypedContractMethod<[siteId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSite"
  ): TypedContractMethod<
    [siteId: BytesLike],
    [
      [string, boolean, bigint] & {
        owner: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSiteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isGatewayAuthorized"
  ): TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSignerAuthorized"
  ): TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerSite"
  ): TypedContractMethod<[siteId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeGateway"
  ): TypedContractMethod<
    [siteId: BytesLike, gateway: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSigner"
  ): TypedContractMethod<
    [siteId: BytesLike, signer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "siteIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sites"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint] & {
        owner: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [siteId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GatewayAuthorized"
  ): TypedContractEvent<
    GatewayAuthorizedEvent.InputTuple,
    GatewayAuthorizedEvent.OutputTuple,
    GatewayAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "GatewayRevoked"
  ): TypedContractEvent<
    GatewayRevokedEvent.InputTuple,
    GatewayRevokedEvent.OutputTuple,
    GatewayRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SignerAuthorized"
  ): TypedContractEvent<
    SignerAuthorizedEvent.InputTuple,
    SignerAuthorizedEvent.OutputTuple,
    SignerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "SignerRevoked"
  ): TypedContractEvent<
    SignerRevokedEvent.InputTuple,
    SignerRevokedEvent.OutputTuple,
    SignerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SiteDeactivated"
  ): TypedContractEvent<
    SiteDeactivatedEvent.InputTuple,
    SiteDeactivatedEvent.OutputTuple,
    SiteDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "SiteOwnershipTransferred"
  ): TypedContractEvent<
    SiteOwnershipTransferredEvent.InputTuple,
    SiteOwnershipTransferredEvent.OutputTuple,
    SiteOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SiteRegistered"
  ): TypedContractEvent<
    SiteRegisteredEvent.InputTuple,
    SiteRegisteredEvent.OutputTuple,
    SiteRegisteredEvent.OutputObject
  >;

  filters: {
    "GatewayAuthorized(bytes32,address,uint256)": TypedContractEvent<
      GatewayAuthorizedEvent.InputTuple,
      GatewayAuthorizedEvent.OutputTuple,
      GatewayAuthorizedEvent.OutputObject
    >;
    GatewayAuthorized: TypedContractEvent<
      GatewayAuthorizedEvent.InputTuple,
      GatewayAuthorizedEvent.OutputTuple,
      GatewayAuthorizedEvent.OutputObject
    >;

    "GatewayRevoked(bytes32,address,uint256)": TypedContractEvent<
      GatewayRevokedEvent.InputTuple,
      GatewayRevokedEvent.OutputTuple,
      GatewayRevokedEvent.OutputObject
    >;
    GatewayRevoked: TypedContractEvent<
      GatewayRevokedEvent.InputTuple,
      GatewayRevokedEvent.OutputTuple,
      GatewayRevokedEvent.OutputObject
    >;

    "SignerAuthorized(bytes32,address,uint256)": TypedContractEvent<
      SignerAuthorizedEvent.InputTuple,
      SignerAuthorizedEvent.OutputTuple,
      SignerAuthorizedEvent.OutputObject
    >;
    SignerAuthorized: TypedContractEvent<
      SignerAuthorizedEvent.InputTuple,
      SignerAuthorizedEvent.OutputTuple,
      SignerAuthorizedEvent.OutputObject
    >;

    "SignerRevoked(bytes32,address,uint256)": TypedContractEvent<
      SignerRevokedEvent.InputTuple,
      SignerRevokedEvent.OutputTuple,
      SignerRevokedEvent.OutputObject
    >;
    SignerRevoked: TypedContractEvent<
      SignerRevokedEvent.InputTuple,
      SignerRevokedEvent.OutputTuple,
      SignerRevokedEvent.OutputObject
    >;

    "SiteDeactivated(bytes32,uint256)": TypedContractEvent<
      SiteDeactivatedEvent.InputTuple,
      SiteDeactivatedEvent.OutputTuple,
      SiteDeactivatedEvent.OutputObject
    >;
    SiteDeactivated: TypedContractEvent<
      SiteDeactivatedEvent.InputTuple,
      SiteDeactivatedEvent.OutputTuple,
      SiteDeactivatedEvent.OutputObject
    >;

    "SiteOwnershipTransferred(bytes32,address,address)": TypedContractEvent<
      SiteOwnershipTransferredEvent.InputTuple,
      SiteOwnershipTransferredEvent.OutputTuple,
      SiteOwnershipTransferredEvent.OutputObject
    >;
    SiteOwnershipTransferred: TypedContractEvent<
      SiteOwnershipTransferredEvent.InputTuple,
      SiteOwnershipTransferredEvent.OutputTuple,
      SiteOwnershipTransferredEvent.OutputObject
    >;

    "SiteRegistered(bytes32,address,uint256)": TypedContractEvent<
      SiteRegisteredEvent.InputTuple,
      SiteRegisteredEvent.OutputTuple,
      SiteRegisteredEvent.OutputObject
    >;
    SiteRegistered: TypedContractEvent<
      SiteRegisteredEvent.InputTuple,
      SiteRegisteredEvent.OutputTuple,
      SiteRegisteredEvent.OutputObject
    >;
  };
}
